server:
  port: 8029
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.198.114.212:3306:3306/visiondb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.vs.vision.pojo.sys    #别名包
  mapper-locations: /mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true